import { SignIn } from "@clerk/clerk-react";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Logo from "../images/logo.png";
import {
  IconBrandDiscord,
  IconBrandGithub,
  IconBrandGoogle,
} from "@tabler/icons-react";
import { Montserrat_Alternates } from "next/font/google";

const montserratAlt = Montserrat_Alternates({
  weight: "400",
  subsets: ["latin"],
});

const Login = () => {
  return (
    <div className="flex flex-col items-center justify-center">
      <Image src={Logo} width={150} height={100} alt="logo" />
      <p className="p-10 text-center text-2xl italic text-[#347355]">
        A place to write your thoughts, <br /> or your favorite's quotes from
        books <br /> or songs.
      </p>
      <p className="text-center text-xl font-medium  text-[#CCC]">
        You can login with:
      </p>
      <div className="flex gap-14 p-10">
        <IconBrandDiscord size={38} color="#347355" />
        <IconBrandGithub size={38} color="#347355" />
        <IconBrandGoogle size={38} color="#347355" />
      </div>
    </div>
  );
};

export default function Home() {
  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center ${montserratAlt.className}`}
      >
        <div className="flex h-screen w-full items-center justify-center bg-[#223240]">
          {!isSignedIn && (
            <div className="flex h-screen w-full flex-col items-center justify-center">
              <Login />
              <SignInButton mode="modal">
                <button className="rounded-full bg-[#347355] px-4 py-2 text-lg font-bold text-[#223240] transition-all duration-500  hover:scale-105 hover:bg-[#93D94E]">
                  Click Here!
                </button>
              </SignInButton>
            </div>
          )}
          {!!isSignedIn && <SignOutButton />}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
}
