import Head from "next/head";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { Montserrat_Alternates } from "next/font/google";
import { api } from "~/utils/api";
import { PostView } from "~/components/PostView";
import { PrincipalPage } from "~/components/PrincipalPage";
import { CreatePostWizard } from "~/components/CreatePostWizard";

dayjs.extend(relativeTime);

const montserratAlt = Montserrat_Alternates({
  weight: "400",
  subsets: ["latin"],
});

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  // if (isLoading) return <div>Loading...</div>;

  // if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>SAYT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex h-screen justify-center ${montserratAlt.className}`}
      >
        <div className="h-full w-full  md:max-w-2xl">
          <div className="flex  border-b border-slate-400 p-4 ">
            {!user.isSignedIn && (
              <div className="flex h-screen w-full flex-col items-center justify-center">
                <PrincipalPage />
                <SignInButton mode="modal">
                  <button className="rounded-full bg-[#347355] px-4 py-2 text-lg font-bold text-[#223240] transition-all duration-500  hover:scale-105 hover:bg-[#93D94E]">
                    Click Here!
                  </button>
                </SignInButton>
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          {user.isSignedIn && (
            <div className="flex flex-col">
              {data?.map((fullPost) => (
                <PostView {...fullPost} key={fullPost.post.id} />
              ))}
              <SignOutButton />
            </div>
          )}
        </div>
      </main>
    </>
  );
}
